spring.application.name=Torneos-api
spring.datasource.url=jdbc:postgresql://localhost:5432/torneos_db
spring.datasource.username=postgres
spring.datasource.password=1023801019
spring.jpa.hibernate.ddl-auto=validate


